CREATE DATABASE freelance_db;
USE freelance_db;

-- ADMIN
CREATE TABLE ADMIN (
  Admin_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Password VARCHAR(200) NOT NULL
);

-- CLIENT
CREATE TABLE CLIENT (
  Client_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Password VARCHAR(200) NOT NULL,
  Company_Name VARCHAR(150),
  Registered_On DATE DEFAULT (CURRENT_DATE)
);

-- STUDENT
CREATE TABLE STUDENT (
  Student_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Password VARCHAR(200) NOT NULL,
  Skills VARCHAR(300),
  CGPA DECIMAL(3,2),
  Registered_On DATE DEFAULT (CURRENT_DATE)
);

-- PROJECT
CREATE TABLE PROJECT (
  Project_ID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(200) NOT NULL,
  Description TEXT,
  Budget DECIMAL(10,2),
  Deadline DATE,
  Status ENUM('Open','Assigned','Completed','Closed') DEFAULT 'Open',
  Client_ID INT NOT NULL,
  FOREIGN KEY (Client_ID) REFERENCES CLIENT(Client_ID) ON DELETE CASCADE
);

-- APPLICATION
CREATE TABLE APPLICATION (
  App_ID INT PRIMARY KEY AUTO_INCREMENT,
  Student_ID INT NOT NULL,
  Project_ID INT NOT NULL,
  Status ENUM('Pending','Approved','Rejected') DEFAULT 'Pending',
  Applied_On DATE DEFAULT (CURRENT_DATE),
  FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID) ON DELETE CASCADE,
  FOREIGN KEY (Project_ID) REFERENCES PROJECT(Project_ID) ON DELETE CASCADE
);

-- ASSIGNMENT
CREATE TABLE ASSIGNMENT (
  Assignment_ID INT PRIMARY KEY AUTO_INCREMENT,
  Project_ID INT UNIQUE,
  Student_ID INT,
  Assigned_On DATE DEFAULT (CURRENT_DATE),
  FOREIGN KEY (Project_ID) REFERENCES PROJECT(Project_ID),
  FOREIGN KEY (Student_ID) REFERENCES STUDENT(Student_ID)
);

USE freelance_db;

CREATE TABLE CATEGORY (
  Category_ID INT PRIMARY KEY AUTO_INCREMENT,
  Category_Name VARCHAR(100) NOT NULL UNIQUE
);

